server:
  port: 8081

userCrud:
  url: localhost:8080
  context-path: api/v1

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          configuration:
            auto-offset-reset: latest
      bindings:
        users:
          group: input-group
          consumer:
            max-attempts: 1
            autoCommitOffset: true
            autoCommitOnError: false