server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_default: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/machete
    username: postgres
    password: 123123

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

logging:
  level:
    ROOT: DEBUG